[package]
name = "iced_command_runner"
version = "0.3.52"
edition = "2024"
description = "An iced widget that spawns child command line process, execute commands, streams its outputs, and displays them in a mocked terminal window."
readme = "README.md"
license = "MIT"
repository = "https://github.com/Yiheng-Yu/iced-command-runner.git"
keywords = ["iced", "widget", "command"]
categories = ["gui"]
exclude = [
    ".gitignore"
]

[[example]]
name = "pbar"
path = "examples/pbar/src/main.rs"

[[example]]
name = "custom_layout"
path = "examples/custom_layout.rs"

[[example]]
name = "default_layout"
path = "examples/default_layout.rs"

[[example]]
name = "multiple_window"
path = "examples/multiple_window.rs"


[profile.release]
opt-level = 3
overflow-checks = true
debug-assertions = false
incremental = true
strip = true
lto = true

[dev-dependencies]
futures = "0.3.32"

[patch.crates-io]
iced_core.git = "https://github.com/iced-rs/iced"
iced_runtime.git = "https://github.com/iced-rs/iced"
iced_widget.git = "https://github.com/iced-rs/iced"
iced_winit.git = "https://github.com/iced-rs/iced"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", features = [
    'advanced',
    'debug',
    'tokio',
] }
iced_core = { git = "https://github.com/iced-rs/iced" }
iced_runtime = { git = "https://github.com/iced-rs/iced" }
iced_widget = { git = "https://github.com/iced-rs/iced" }
iced_winit = { git = "https://github.com/iced-rs/iced" }
log = "0.4.33"
tokio = { version = "1.52.3", features = ["full"] }
