[package]
name = "iced_command_runner"
version = "0.1.2"
edition = "2024"
description = "An iced GUI widget for execute termianl commands and streaming output."
readme = "README.md"
repository = "https://github.com/Yiheng-Yu/iced-command-runner.git"
license-file = "LICENSE"
keywords = ["iced", "widget", "command"]
categories = ["gui"]
exclude = [
    ".gitignore"
]


[dev-dependencies]
futures = "0.3.32"


[dependencies]
anyhow = "1.0.102"
iced = { version = "0.14.0", features = [
    'advanced',
    'debug',
    'tokio',
] }
iced_core = "0.14.0"
log = "0.4.33"
tokio = { version = "1.52.3", features = ["full"] }
