[package]
name = "iced_command_runner"
version = "0.1.33"
edition = "2024"
description = "An iced widget that spawns child command line process, execute commands, streams its outputs, and displays them in a mocked terminal window."
readme = "README.md"
license = "MIT"
repository = "https://github.com/Yiheng-Yu/iced-command-runner.git"
keywords = ["iced", "widget", "command"]
categories = ["gui"]
exclude = [
    ".gitignore"
]


[dev-dependencies]
futures = "0.3.32"


[dependencies]
iced = { version = "0.14.0", features = [
    'advanced',
    'debug',
    'tokio',
] }
iced_core = "0.14.0"
log = "0.4.33"
tokio = { version = "1.52.3", features = ["full"] }
